version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Setup
          command: echo Setup.
      - run:
          name: Print the Current Time
          command: date
